### ISSUE TITLE
Question: Run in the browser?

### ISSUE THREAD

**Issue by theSherwood** [GGabi/RippleDB#3]
Hi @GGabi,
I'm looking for a fast triplestore I can run in a worker in memory in a browser. I notice that you have two triplestore libraries you are working on. OjiDB and RippleDB. Which one is closest to being able to run in memory in the browser and what are some obstacles you see to making that work.

Ultimately, I need a fast triplestore db that can run in the browser or on the backend with a syncing layer that would accommodate a connector to indexedDB and filestystem API's. I haven't done any real work in rust, but I would be interested in contributing to whichever of your libraries you most recommend.

Cheers!

**Comment by GGabi** [comment]
Hi @theSherwood ,

I'm honoured that you've considered either of my projects!

RippleDB is the library I'm currently working on as part of my dissertation due this May, but I intend to continue development after university.

Ripple can already be included in any Rust program, so it shouldn't be a stretch to get it working as part of a backend provided you create the handles to Ripple's API. All of the functionality it currently has, including persisting to the filesystem, is documented in the COOKBOOK.md file in the root of the repo.

I know very little about indexedDB so I can only talk generally, but it doesn't seem like a huge task to export the contents of a RippleDB instance for persistence. Most of the functionality needed to export the contents of a database instance to JSON is already in the library, it would just need some extra engineering to get it working. Implementing this feature to work quickly with extremely large datasets would be much more difficult, however. I'd be more than happy to accept useful, meaningful contributions like this if you're interested in taking up the task :D

As a side note, one of my original ideas for my dissertation was to develop a database that can be run in the front-end using WebAssembly. However, I ran into issues persisting data long-term because WebAssembly is sand-boxed by design. It seemed much more practical to just develop a library for a backend instead. Other than this issue, I'm not aware of any reason why a triplestore such as Ripple couldn't be adapted to run in-browser.

Sorry for the late reply, I'm sure you understand given the state of the world right now 😅

**Comment by theSherwood** [comment]
> Sorry for the late reply, I'm sure you understand given the state of the world right now 😅

Of course! I appreciate you replying at all!

> Most of the functionality needed to export the contents of a database instance to JSON is already in the library, it would just need some extra engineering to get it working. Implementing this feature to work quickly with extremely large datasets would be much more difficult, however. 

I'm wondering if the thing to do would be to throw in a hook interface so that registered hooks get called with any changes to the database. If those changes could be hooked into so that messages could be posted to different threads (workers), then IndexedDB could be kept up to date incrementally (in another worker) without having to export and persist the database on every change. The hook thing would also be more general (allowing a reactive layer of a syncing layer on top of the database).

> RippleDB is the library I'm currently working on as part of my dissertation due this May, but I intend to continue development after university.

I confess that I've looked more closely at OjiDB because it seems simpler, and as someone with no real Rust experience, simpler is pretty attractive. But I noticed that OjiDB uses nested hashmaps as the database structure whereas RippleDB uses k2-trees. I'm unfamiliar with k2-trees and was unable to find any clear resources on them online. Could you talk me through these different design decisions? What were the limitations of hashmaps in OjiDB that caused you to go with k2-trees in RippleDB?

I actually have a few questions? Feel free to not answer all/any of them:

It seems that in OjiDB, at least, the only data type supported is String. Is there any possibility of extending that? Could arrays of strings also be supported, for example?

How about full-text search? Do you see any major impediments to supporting that?

Anyway, like I said, feel free to be selective about answering any of my questions. I'm likely to have many more and I don't want to monopolize your time.

---

Sidenote: The needs of my project actually require a database more like [Datomic](https://docs.datomic.com/cloud/index.html). Basically a triplestore with 2 additional columns for transaction ids and whether the fact has been added or removed from the database. I'm still trying to figure out the exact design of the database I need, but I think a triplestore is a good place to start.  

If I can help setup one of your triplestores for syncing, persisting to indexedDB, etc. then I can fork that and make whatever changes to the data model that I might need to make for the particular requirements of my project.

**Comment by GGabi** [comment]
> I'm wondering if the thing to do would be to throw in a hook interface so that registered hooks get called with any changes to the database. If those changes could be hooked into so that messages could be posted to different threads (workers), then IndexedDB could be kept up to date incrementally (in another worker) without having to export and persist the database on every change. The hook thing would also be more general (allowing a reactive layer of a syncing layer on top of the database).

At the risk of sounding stupid, it sounds like you want to maintain two databases with exactly the same info stored inside: one in an in-memory triplestore, the other in a persisted indexedDB. If that is the case, what's stopping you from simply duplicating the CRUD requests within the API rather than placing the burden on any single datastore?

> I confess that I've looked more closely at OjiDB because it seems simpler, and as someone with no real Rust experience, simpler is pretty attractive. But I noticed that OjiDB uses nested hashmaps as the database structure whereas RippleDB uses k2-trees. I'm unfamiliar with k2-trees and was unable to find any clear resources on them online. Could you talk me through these different design decisions? What were the limitations of hashmaps in OjiDB that caused you to go with k2-trees in RippleDB?

So OjiDB was based on the [Hexastore](https://people.csail.mit.edu/tdanford/6830papers/weiss-hexastore.pdf) design, which was a great introduction to triplestores and graph databases generally. However, hashing operations aren't very computationally cheap so I soon realised it wasn't the best implementation for a "high speed" database 😅. Plus, research has shown that this is no longer a cutting-edge design.
More in-depth research brought me to [this paper](http://swp.dcc.uchile.cl/TR/2009/TR_DCC-20090429-005.pdf), and more googling revealed that other than the papers I could find on it no one seems to be using the K2-Tree. I can explain a bit but it's a large topic so I advise you read the paper regardless.
The K2-Tree is a data structure designed to be very good at compressing sparsely populated bit-matrices (loads of 0s). Other papers have covered in detail how to represent a triple-store with a series of bit-matrices, using Vertical Partitioning. Other studies have also shown that a majority of graph-datasets tend to be quite sparse when represented as bit-matrices. So, with the help of yet more papers, I implemented RippleDB with using this method.
I chose K2-Trees because they are very space-efficient and are much faster than any hash-map (as almost all operations are just traversals of contiguous bits). Plus, with the time-restrictions uni placed on me, it was more doable compared to other approaches like structural indexing.

> It seems that in OjiDB, at least, the only data type supported is String. Is there any possibility of extending that? Could arrays of strings also be supported, for example?

Yup, you can store any type in hashmaps. Just change the type signature of the Graph struct and fix any errors that pop up.

> How about full-text search? Do you see any major impediments to supporting that?

What do you mean by full-text search?

> Sidenote: The needs of my project actually require a database more like [Datomic](https://docs.datomic.com/cloud/index.html). Basically a triplestore with 2 additional columns for transaction ids and whether the fact has been added or removed from the database. I'm still trying to figure out the exact design of the database I need, but I think a triplestore is a good place to start.

By columns, do you mean that each relation in the database will be a Quintuple rather than a Triple?
Triple-Stores are very good a representing highly-connected data,  or data that doesn't tend to follow a specific schema. Graph databases generally are useful for representing datasets where the structure of the data matters just as much as the data itself (think social graphs). For predictable data, I can't really think of a reason not to use a relational database.

**Comment by theSherwood** [comment]
> At the risk of sounding stupid, it sounds like you want to maintain two databases with exactly the same info stored inside: one in an in-memory triplestore, the other in a persisted indexedDB. If that is the case, what's stopping you from simply duplicating the CRUD requests within the API rather than placing the burden on any single datastore?

That is a possibility. My thinking is that I want one source of truth (the in-memory db) with a syncing layer that everything else refers to. The ui and indexeddb will both be looking to the in-memory db. The syncing layer will make sure that what gets into the in-memory db will eventually get persisted to indexeddb even if it fails at first. Otherwise, it seems like (should errors occur) the 2 databases could drift apart.

> I chose K2-Trees because they are very space-efficient and are much faster than any hash-map (as almost all operations are just traversals of contiguous bits).

Okay. Very cool. Thanks for the resources. Looks like I've got some reading to do! 

> Yup, you can store any type in hashmaps. Just change the type signature of the Graph struct and fix any errors that pop up.

Is this also true of the K2-Trees?

> What do you mean by full-text search?

If I store a long string (an entire article, say) in a triple ([<subject> <predicate> article]), can I find the triple by querying for a word that appears in the article?

> By columns, do you mean that each relation in the database will be a Quintuple rather than a Triple?

Yes. I didn't know the proper way to express that.

> Graph databases generally are useful for representing datasets where the structure of the data matters just as much as the data itself (think social graphs). For predictable data, I can't really think of a reason not to use a relational database.

Yes, for this reason I need a graph database. I need to be able to support unpredictable, user-generated relations. However, I also need to be able to annotate each of those triples with the time that 'fact' (they are referred to as 'facts' in Datomic 🤷‍♂ ) was add to or removed from the database. That allows for some pretty handy queries given what I'm trying to do. But that subject-predicate-object relationship (or entity-attribute-value as it is in Datomic) needs to be able to support unpredictable structured data. That's why I want to start with a Triplestore.

**Comment by GGabi** [comment]
> That is a possibility. My thinking is that I want one source of truth (the in-memory db) with a syncing layer that everything else refers to. The ui and indexeddb will both be looking to the in-memory db. The syncing layer will make sure that what gets into the in-memory db will eventually get persisted to indexeddb even if it fails at first. Otherwise, it seems like (should errors occur) the 2 databases could drift apart.

Ah okay, at this point I think it may actually be able to implement this as an abstraction over RippleDB in your software, rather than trying to bake it into the library. What I would look to do would be to maintain a transaction history and propagate those transactions yourself to the IndexedDB. All the update methods on a Ripple instance return a Result type, so you'll know instantly whether an update failed to be applied to the in-memory model and can react accordingly. If need be, it's always possible to query the in-memory database to verify specific aspects of its contents to diff with any other store.

> Is this also true of the K2-Trees?

K2-Trees are only ever useful for representing bit-matrices, so if you can represent something using a bit-matrix (like a graph's structure) then you can use K2-Trees. Perhaps I missed something out before, as you can see in the `Graph` struct definition I have two `BiBTreeMap`s which are effectively dictionaries. These map unique entities in a dataset to a unique number, corresponding to rows and columns in the bit-matrices encoded using K2-Trees. Without going into any more specifics on exactly how it works, changing the types that these `BiBTreeMap`s use to map to `usize`s will allow you to store any type you want in there, even collections. Just make sure whatever type you're using implements all the required traits like Eq, PartialOrd etc.

> If I store a long string (an entire article, say) in a triple (`[<subject> <predicate> article]`), can I find the triple by querying for a word that appears in the article?

That would be really cool, but right now I can't think of an easy way to do it without either:
- Further indexing the data inside the Graph, which would increase the memory-footprint of the database (not good)
- Brute force search everything whenever you attempt this in a query (also not good)
But having said that, if you have any ideas I'd love to hear them!

> Yes. I didn't know the proper way to express that.

I'm not sure how to encode a dataset of Quintuples using bit-matrices, so at the moment I don't think it's possible. You could emulate it using triples if you really wanted to:
[A -> B ->  C], [C -> D -> E]
If there's a way to easily vertically partition Quintuples into bit-matrices, then it would instantly become possible. If you find any let me know :D

> Yes, for this reason I need a graph database. I need to be able to support unpredictable, user-generated relations. However, I also need to be able to annotate each of those triples with the time that 'fact' (they are referred to as 'facts' in Datomic 🤷‍♂ ) was add to or removed from the database. That allows for some pretty handy queries given what I'm trying to do. But that `subject-predicate-object` relationship (or `entity-attribute-value` as it is in Datomic) needs to be able to support unpredictable structured data. That's why I want to start with a Triplestore.

This sounds like you could benefit from either a Property Graph or Document Graph database rather than a pure triplestore, seeing as you want to encode relations with extra properties. As a quick note, it would be very easy to add this to Oji by adding extra layers of Hashmaps or having the lowest levels be a collection of data. In Ripple, however, it's definitely not trivial to implement :/

**Comment by theSherwood** [comment]
> Ah okay, at this point I think it may actually be able to implement this as an abstraction over RippleDB in your software, rather than trying to bake it into the library. What I would look to do would be to maintain a transaction history and propagate those transactions yourself to the IndexedDB. All the update methods on a Ripple instance return a Result type, so you'll know instantly whether an update failed to be applied to the in-memory model and can react accordingly. If need be, it's always possible to query the in-memory database to verify specific aspects of its contents to diff with any other store.

Excellent! Is there a similar construct in OjiDB?

> K2-Trees are only ever useful for representing bit-matrices, so if you can represent something using a bit-matrix (like a graph's structure) then you can use K2-Trees. Perhaps I missed something out before, as you can see in the Graph struct definition I have two BiBTreeMaps which are effectively dictionaries. These map unique entities in a dataset to a unique number, corresponding to rows and columns in the bit-matrices encoded using K2-Trees. Without going into any more specifics on exactly how it works, changing the types that these BiBTreeMaps use to map to usizes will allow you to store any type you want in there, even collections. Just make sure whatever type you're using implements all the required traits like Eq, PartialOrd etc.

Gotcha. Trying to wrap my head around that. But I will get there.

> That would be really cool, but right now I can't think of an easy way to do it without either: 

> Further indexing the data inside the Graph, which would increase the memory-footprint of the database (not good)

That's sort of what I'm thinking. From the extremely limited amount I understand about databases, that's what's done: extra indices. I'm thinking though that this might be best done as a partial index, because it is unlikely that you'd want every S-P combination to have an O indexed for full-text search. More likely you'd have just some P for which you'd want the O indexed for full-text search. So let's say you have your SOP, POS, OSP indices. Maybe the way to do this is have an additional partial POS, or OSP just for full-text search. Only relations with the necessary P get indexed into this full-text index. That's kind of heavy, but I don't think there is any way to do a fast full-text search without more indexing.

Done that way, it wouldn't need to be in the library.

> I'm not sure how to encode a dataset of Quintuples using bit-matrices, so at the moment I don't think it's possible. You could emulate it using triples if you really wanted to:
[A -> B -> C], [C -> D -> E]
> If there's a way to easily vertically partition Quintuples into bit-matrices, then it would instantly become possible. If you find any let me know :D

I know nothing about this topic but I will try to find out. Haha

> This sounds like you could benefit from either a Property Graph or Document Graph database rather than a pure triplestore, seeing as you want to encode relations with extra properties. 

A property graph feels like overkill, because the only other data I need is the transaction id and maybe 1 other field. I don't need to be able to add arbitrary properties to relations.

> As a quick note, it would be very easy to add this to Oji by adding extra layers of Hashmaps or having the lowest levels be a collection of data. In Ripple, however, it's definitely not trivial to implement :/

That's sort of why I've been looking at Oji, because I can sort of imagine implementing the extra hashmap layers. I don't have much of a clue about the k2-trees yet.

---

Okay. Looks like I've got a fair bit I need to study up on with k2-trees and bit matrices. Thanks for all the info.

**Comment by theSherwood** [comment]
Okay. I'm back with a slew of questions. Mostly about k2-trees and how you are mapping triples onto the trees.

In the paper you linked to, the web graph one, the adjecency graph/bit matrix answers the question: For each member of this set of web pages, for which web pages is there a link. So the bit matrix was showing a set intersecting with itself. That graph was then encoded/compressed into k2-trees.

But in the case of a triplestore, you don't have a set intersecting with itself. You have a set (subjects) intersecting with another set (predicates) intersecting with another set (objects). Which seems to me like it ought to be a 3d adjacency graph (which could then be encoded/compressed into k-trees of some kind).

But looking at the Ripple code, it looks like subjects and objects are both in a `dict` BiBTreeMap while predicates are in a `predicates` BiBTreeMap. On top of that you also have `slices` and `dictTombstones` and `predTombstones`. `slices` appears to be a vector of k-trees?

If it isn't too much trouble, could you give me a high-level overview of what each of these pieces is doing? I think I'm starting to get it, but I want to make sure I'm on the right track.

**Comment by GGabi** [comment]
Hi, awesome to see you taking an interest!

Yeah, you are right that the paper I linked you to only explained how to represent Web-Graphs but there isn't much difference between this and representing a Triplestore. You can think of the web-graph shown as a subset of a triplestore.

A web-graph like in that paper I linked is effectively a triplestore with one predicate: "is linked to". You can easily extend the principle to triplestore by having one k2-tree, or bit-matrix, per predicate. This is exactly what I do, and the reason why `dict` and `predicates` are separate is because a Graph has exactly one K2-Tree per predicate, with each column/row representing a object/subject from `dict`.  You can ignore the tombstones, for now, that's just to make deletion a bit faster.

Here's a paper that hopefully explains it a bit better:
[Compressed k2-Triples for Full-In-Memory RDF Engines](https://arxiv.org/ftp/arxiv/papers/1105/1105.4004.pdf)

**Comment by theSherwood** [comment]
Thanks for the link and the explanation! That sheds a lot of light on this.

> You can ignore the tombstones, for now, that's just to make deletion a bit faster.

So you need tombstones because inserts and deletes are slow, right? So you use tombstones so that you can amortize the cost of deletes. Do you do anything to amortize the cost of inserts?

**Comment by GGabi** [comment]
Here's an excerpt from the Wikipedia for the Tombstone pattern:

"In more generalized terms, a tombstone can be understood as a marker for "this data is no longer here". For example, in filesystems it may be efficient when deleting files to mark them as "dead" instead of immediately reclaiming all their data blocks."

If you think of the subjects/objects/predicates as elements stored in a list, which is kind of what I'm doing, then this is what happens: When an element is deleted from the end of the list, that's fine you can easily chop off the end of the list and call it a day. However, if we want to delete an element from the middle of a list then we get into some issues. Because elements in `dict` and `predicates` are mapped to a specific number, let's call it their position in their list, naively moving all elements after the deleted back one space would ruin all of the book-keeping as everything is now out of place. 
Instead, when removing the element in the middle of the list I just set it to a Null value and store the position of this dead value in a list. Then, any insertions of new data will check if there are any "dead" spot to fill before being pushed onto the end.
Because databases are expected to store upwards of millions of pieces of data, having to move large portions of it in memory after every delete operation isn't sensible, so this has the benefit of preventing moves as often.

**Comment by theSherwood** [comment]
Right. That makes sense. 

> Then, any insertions of new data will check if there are any "dead" spot to fill before being pushed onto the end.

You just push inserts onto the ends of the lists (if there is no convenient tombstone to fill)? So you don't need to maintain any kind of sort order?

**Comment by GGabi** [comment]
No because while the analogy uses a list, in reality, I'm using a BTreeMap which maps each element to a unique id. "Pushing onto the end" simply corresponds to giving it an id one higher than the previous highest.
I plan on implementing a "squish" method that take's it's time to refactor the contents to the most efficient arrangement (commonly used id's clumped together to maximise the benefits of k2-trees etc.) but I don't have time to implement that before the deadline of my diss

**Comment by theSherwood** [comment]
Ah. Okay. So how do you search for ranges of things? Or an object less than a certain value, for example?

**Comment by GGabi** [comment]
> Ah. Okay. So how do you search for ranges of things? Or an object less than a certain value, for example?

I don't ever need to, which is why I chose BTreeMap rather than a list
